DOCKERUSER?=sigsci
DOCKERNAME?=sigsci-apache-ubuntu1604
DOCKERTAG?=latest
SIGSCI_ACCESSKEYID?=SETME
SIGSCI_SECRETACCESSKEY?=SETME
SIGSCI_HOSTNAME?=alpine35
DOCKERMOUNT?="/var/run/sigsci/agent.sock"

build:
	./getAgent.sh
	docker build -t $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG) .

build-no-cache:
	./getAgent.sh
	docker build --no-cache -t $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG) .

run:
<<<<<<< HEAD
	docker run -p 8080:8080 --name $(DOCKERNAME) -d -e SIGSCI_HOSTNAME=$(SIGSCI_HOSTNAME)  -e SIGSCI_ACCESSKEYID=$(SIGSCI_ACCESSKEYID) -e SIGSCI_SECRETACCESSKEY=$(SIGSCI_SECRETACCESSKEY) $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG)
=======
	docker run -p 8080:8080 --name $(DOCKERNAME) -d -e SIGSCI_HOSTNAME=$(SIGSCI_HOSTNAME)  -e SIGSCI_ACCESSKEYID="$(SIGSCI_ACCESSKEYID)" -e SIGSCI_SECRETACCESSKEY="$(SIGSCI_SECRETACCESSKEY)" $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG)
>>>>>>> 0abb64ef722deb32eeb8edfcef80049348ed5ec6

deploy:
	docker push $(DOCKERUSER)/$(DOCKERNAME):$(DOCKERTAG)
