#!/bin/sh
ACCESSKEY=$SIGSCI_ACCESSKEY
SECRETKEY=$SIGSCI_SECRETKEY
RPCADDRESS=$SIGSCI_RPCADDRESS
DOCKERID=`hostname`
INSTHOST="$SIGSCI_HOSTNAME-$DOCKERID"
export SIGSCI_SERVER_HOSTNAME=$INSTHOST


/usr/local/bin/httpd-foreground &
/usr/sbin/sigsci-agent 
#/usr/sbin/apache2 -DFOREGROUND
